use hospital;
select * from historiaclinica;
insert into medicos values (1,'Juan ','1973-12-09','1');
insert into medicos values (2,'Jorge ','1955-09-26','3');
insert into medicos values (3,'Maria ','1986-04-14','2');
insert into pacientes values (1,'Hector','HFS56253');
insert into pacientes values (2,'Angel','HFS2344');
insert into pacientes values (3,'Alison','HFS5689');
insert into pacientes values (4,'Carlos','HFS1245');
insert into pacientes values (5,'Ximena','HFS4578');
insert into pacientes values (6,'Emmanuel','HFS7812');
insert into pacientes values (7,'ALberto','GS31785');
insert into pacientes values (8,'Erick','ER8523');
insert into pacientes values (9,'Fatima','HS85321');
insert into pacientes values (10,'Sebastian','FR63784');
insert into pacientes values (11,'Sebastian','FR63784');
insert into pacientes values (12,'Angel','HFS2344');
insert into historiaclinica values ('12345','1996-05-26','Sintomas de precion alta',5,2);
select * from pacientes;
select distinct nombrepaciente from pacientes;
select count (distinct nombrepaciente) from pacientes;
select * from pacientes where nombrepaciente like 'A%';
select * from hospital where nombrehospital='imss';
select * from pacientes where nombrepaciente like 'A%' or nombrepaciente like 'E%';
select * from pacientes where not nombrepaciente like 'A%';
select * from pacientes order by nombrepaciente asc;
select * from pacientes order by nombrepaciente desc;
